apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar-pod
  name: sidecar-pod
  namespace: lab3
spec:
  containers:
  - name: busybox
    image: busybox
    resources: {}
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do date >> /var/log/date.log; sleep 5; done"
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - name: nginx
    image: nginx
    resources: {}
    volumeMounts:
    - name: logs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: logs
    hostPath:
      path: /mnt/logs
      type: DirectoryOrCreate
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
